// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjHTu-xOd6KlwaGEkTXRaAFhr82GIjs_Y',
    appId: '1:636242533270:web:97bc1ccdd473ce6e509bb7',
    messagingSenderId: '636242533270',
    projectId: 'sheet-manager-excel-addin',
    authDomain: 'sheet-manager-excel-addin.firebaseapp.com',
    storageBucket: 'sheet-manager-excel-addin.appspot.com',
    measurementId: 'G-639VE1LYQ7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0_LjNgwM_gfAwDiL4RfgXnfWA_XDEN-A',
    appId: '1:636242533270:ios:866e4371e3623cfb509bb7',
    messagingSenderId: '636242533270',
    projectId: 'sheet-manager-excel-addin',
    storageBucket: 'sheet-manager-excel-addin.appspot.com',
    iosClientId: '636242533270-ilt2tqdhd2trks9mu30m5v143lj6cgi2.apps.googleusercontent.com',
    iosBundleId: 'com.example.sheetManager',
  );
}
